#ifndef CSAV_LOCATIONS_H
#define CSAV_LOCATIONS_H

enum PkmnLocations {
    PKMN_LOCATION_LITTLEROOT_TOWN,             // 0x00
    PKMN_LOCATION_OLDALE_TOWN,                 // 0x01
    PKMN_LOCATION_DEWFORD_TOWN,                // 0x02
    PKMN_LOCATION_LAVARIDGE_TOWN,              // 0x03
    PKMN_LOCATION_FALLARBOR_TOWN,              // 0x04
    PKMN_LOCATION_VERDANTURF_TOWN,             // 0x05
    PKMN_LOCATION_PACIFIDLOG_TOWN,             // 0x06
    PKMN_LOCATION_PETALBURG_CITY,              // 0x07
    PKMN_LOCATION_SLATEPORT_CITY,              // 0x08
    PKMN_LOCATION_MAUVILLE_CITY,               // 0x09
    PKMN_LOCATION_RUSTBORO_CITY,               // 0x0A
    PKMN_LOCATION_FORTREE_CITY,                // 0x0B
    PKMN_LOCATION_LILYCOVE_CITY,               // 0x0C
    PKMN_LOCATION_MOSSDEEP_CITY,               // 0x0D
    PKMN_LOCATION_SOOTOPOLIS_CITY,             // 0x0E
    PKMN_LOCATION_EVER_GRANDE_CITY,            // 0x0F
    PKMN_LOCATION_ROUTE_101,                   // 0x10
    PKMN_LOCATION_ROUTE_102,                   // 0x11
    PKMN_LOCATION_ROUTE_103,                   // 0x12
    PKMN_LOCATION_ROUTE_104,                   // 0x13
    PKMN_LOCATION_ROUTE_105,                   // 0x14
    PKMN_LOCATION_ROUTE_106,                   // 0x15
    PKMN_LOCATION_ROUTE_107,                   // 0x16
    PKMN_LOCATION_ROUTE_108,                   // 0x17
    PKMN_LOCATION_ROUTE_109,                   // 0x18
    PKMN_LOCATION_ROUTE_110,                   // 0x19
    PKMN_LOCATION_ROUTE_111,                   // 0x1A
    PKMN_LOCATION_ROUTE_112,                   // 0x1B
    PKMN_LOCATION_ROUTE_113,                   // 0x1C
    PKMN_LOCATION_ROUTE_114,                   // 0x1D
    PKMN_LOCATION_ROUTE_115,                   // 0x1E
    PKMN_LOCATION_ROUTE_116,                   // 0x1F
    PKMN_LOCATION_ROUTE_117,                   // 0x20
    PKMN_LOCATION_ROUTE_118,                   // 0x21
    PKMN_LOCATION_ROUTE_119,                   // 0x22
    PKMN_LOCATION_ROUTE_120,                   // 0x23
    PKMN_LOCATION_ROUTE_121,                   // 0x24
    PKMN_LOCATION_ROUTE_122,                   // 0x25
    PKMN_LOCATION_ROUTE_123,                   // 0x26
    PKMN_LOCATION_ROUTE_124,                   // 0x27
    PKMN_LOCATION_ROUTE_125,                   // 0x28
    PKMN_LOCATION_ROUTE_126,                   // 0x29
    PKMN_LOCATION_ROUTE_127,                   // 0x2A
    PKMN_LOCATION_ROUTE_128,                   // 0x2B
    PKMN_LOCATION_ROUTE_129,                   // 0x2C
    PKMN_LOCATION_ROUTE_130,                   // 0x2D
    PKMN_LOCATION_ROUTE_131,                   // 0x2E
    PKMN_LOCATION_ROUTE_132,                   // 0x2F
    PKMN_LOCATION_ROUTE_133,                   // 0x30
    PKMN_LOCATION_ROUTE_134,                   // 0x31
    PKMN_LOCATION_UNDERWATER_ROUTE_124,        // 0x32
    PKMN_LOCATION_UNDERWATER_ROUTE_126,        // 0x33
    PKMN_LOCATION_UNDERWATER_ROUTE_127,        // 0x34
    PKMN_LOCATION_UNDERWATER_ROUTE_128,        // 0x35
    PKMN_LOCATION_UNDERWATER_SOOTOPOLIS_CITY,  // 0x36
    PKMN_LOCATION_GRANITE_CAVE,                // 0x37
    PKMN_LOCATION_MT_CHIMNEY,                  // 0x38
    PKMN_LOCATION_SAFARI_ZONE,                 // 0x39
    PKMN_LOCATION_BATTLE_TOWER_BATTLE_FRONTIER,// 0x3A
    PKMN_LOCATION_PETALBURG_WOODS,             // 0x3B
    PKMN_LOCATION_RUSTURF_TUNNEL,              // 0x3C
    PKMN_LOCATION_ABANDONED_SHIP,              // 0x3D
    PKMN_LOCATION_NEW_MAUVILLE,                // 0x3E
    PKMN_LOCATION_METEOR_FALLS,                // 0x3F
    PKMN_LOCATION_METEOR_FALLS_UNUSED,         // 0x40
    PKMN_LOCATION_MT_PYRE,                     // 0x41
    PKMN_LOCATION_MAGMA_HIDEOUT_AQUA_HIDEOUT,  // 0x42
    PKMN_LOCATION_SHOAL_CAVE,                  // 0x43
    PKMN_LOCATION_SEAFLOOR_CAVERN,             // 0x44
    PKMN_LOCATION_UNDERWATER_SEAFLOOR_CAVERN,  // 0x45
    PKMN_LOCATION_VICTORY_ROAD,                // 0x46
    PKMN_LOCATION_MIRAGE_ISLAND,               // 0x47
    PKMN_LOCATION_CAVE_OF_ORIGIN,              // 0x48
    PKMN_LOCATION_SOUTHERN_ISLAND,             // 0x49
    PKMN_LOCATION_FIERY_PATH,                  // 0x4A
    PKMN_LOCATION_FIERY_PATH_UNUSED,           // 0x4B
    PKMN_LOCATION_JAGGED_PASS,                 // 0x4C
    PKMN_LOCATION_JAGGED_PASS_UNUSED,          // 0x4D
    PKMN_LOCATION_SEALED_CHAMBER,              // 0x4E
    PKMN_LOCATION_UNDERWATER_ROUTE_134,        // 0x4F
    PKMN_LOCATION_SCORCHED_SLAB,               // 0x50
    PKMN_LOCATION_ISLAND_CAVE,                 // 0x51
    PKMN_LOCATION_DESERT_RUINS,                // 0x52
    PKMN_LOCATION_ANCIENT_TOMB,                // 0x53
    PKMN_LOCATION_INSIDE_OF_TRUCK,             // 0x54
    PKMN_LOCATION_SKY_PILLAR,                  // 0x55
    PKMN_LOCATION_SECRET_BASE,                 // 0x56
    PKMN_LOCATION_FERRY,                       // 0x57
    PKMN_LOCATION_PALLET_TOWN,                 // 0x58
    PKMN_LOCATION_VIRIDIAN_CITY,               // 0x59
    PKMN_LOCATION_PEWTER_CITY,                 // 0x5A
    PKMN_LOCATION_CERULEAN_CITY,               // 0x5B
    PKMN_LOCATION_LAVENDER_TOWN,               // 0x5C
    PKMN_LOCATION_VERMILION_CITY,              // 0x5D
    PKMN_LOCATION_CELADON_CITY,                // 0x5E
    PKMN_LOCATION_FUCHSIA_CITY,                // 0x5F
    PKMN_LOCATION_CINNABAR_ISLAND,             // 0x60
    PKMN_LOCATION_INDIGO_PLATEAU,              // 0x61
    PKMN_LOCATION_SAFFRON_CITY,                // 0x62
    PKMN_LOCATION_ROUTE_4_POKÉMON_CENTER,      // 0x63
    PKMN_LOCATION_ROUTE_10_POKÉMON_CENTER,     // 0x64
    PKMN_LOCATION_ROUTE_1,                     // 0x65
    PKMN_LOCATION_ROUTE_2,                     // 0x66
    PKMN_LOCATION_ROUTE_3,                     // 0x67
    PKMN_LOCATION_ROUTE_4,                     // 0x68
    PKMN_LOCATION_ROUTE_5,                     // 0x69
    PKMN_LOCATION_ROUTE_6,                     // 0x6A
    PKMN_LOCATION_ROUTE_7,                     // 0x6B
    PKMN_LOCATION_ROUTE_8,                     // 0x6C
    PKMN_LOCATION_ROUTE_9,                     // 0x6D
    PKMN_LOCATION_ROUTE_10,                    // 0x6E
    PKMN_LOCATION_ROUTE_11,                    // 0x6F
    PKMN_LOCATION_ROUTE_12,                    // 0x70
    PKMN_LOCATION_ROUTE_13,                    // 0x71
    PKMN_LOCATION_ROUTE_14,                    // 0x72
    PKMN_LOCATION_ROUTE_15,                    // 0x73
    PKMN_LOCATION_ROUTE_16,                    // 0x74
    PKMN_LOCATION_ROUTE_17,                    // 0x75
    PKMN_LOCATION_ROUTE_18,                    // 0x76
    PKMN_LOCATION_ROUTE_19,                    // 0x77
    PKMN_LOCATION_ROUTE_20,                    // 0x78
    PKMN_LOCATION_ROUTE_21,                    // 0x79
    PKMN_LOCATION_ROUTE_22,                    // 0x7A
    PKMN_LOCATION_ROUTE_23,                    // 0x7B
    PKMN_LOCATION_ROUTE_24,                    // 0x7C
    PKMN_LOCATION_ROUTE_25,                    // 0x7D
    PKMN_LOCATION_VIRIDIAN_FOREST,             // 0x7E
    PKMN_LOCATION_MT_MOON,                     // 0x7F
    PKMN_LOCATION_SS_ANNE,                     // 0x80
    PKMN_LOCATION_UNDERGROUND_PATH_ROUTES_5_6, // 0x81
    PKMN_LOCATION_UNDERGROUND_PATH_ROUTES_7_8, // 0x82
    PKMN_LOCATION_DIGLETTS_CAVE,               // 0x83
    PKMN_LOCATION_VICTORY_ROAD_KANTO,          // 0x84
    PKMN_LOCATION_ROCKET_HIDEOUT,              // 0x85
    PKMN_LOCATION_SILPH_CO,                    // 0x86
    PKMN_LOCATION_POKÉMON_MANSION,             // 0x87
    PKMN_LOCATION_SAFARI_ZONE_KANTO,           // 0x88
    PKMN_LOCATION_POKÉMON_LEAGUE,              // 0x89
    PKMN_LOCATION_ROCK_TUNNEL,                 // 0x8A
    PKMN_LOCATION_SEAFOAM_ISLANDS,             // 0x8B
    PKMN_LOCATION_POKÉMON_TOWER,               // 0x8C
    PKMN_LOCATION_CERULEAN_CAVE,               // 0x8D
    PKMN_LOCATION_POWER_PLANT,                 // 0x8E
    PKMN_LOCATION_ONE_ISLAND,                  // 0x8F
    PKMN_LOCATION_TWO_ISLAND,                  // 0x90
    PKMN_LOCATION_THREE_ISLAND,                // 0x91
    PKMN_LOCATION_FOUR_ISLAND,                 // 0x92
    PKMN_LOCATION_FIVE_ISLAND,                 // 0x93
    PKMN_LOCATION_SEVEN_ISLAND,                // 0x94
    PKMN_LOCATION_SIX_ISLAND,                  // 0x95
    PKMN_LOCATION_KINDLE_ROAD,                 // 0x96
    PKMN_LOCATION_TREASURE_BEACH,              // 0x97
    PKMN_LOCATION_CAPE_BRINK,                  // 0x98
    PKMN_LOCATION_BOND_BRIDGE,                 // 0x99
    PKMN_LOCATION_THREE_ISLE_PORT,             // 0x9A
    PKMN_LOCATION_SEVII_ISLE_6,                // 0x9B
    PKMN_LOCATION_SEVII_ISLE_7,                // 0x9C
    PKMN_LOCATION_SEVII_ISLE_8,                // 0x9D
    PKMN_LOCATION_SEVII_ISLE_9,                // 0x9E
    PKMN_LOCATION_RESORT_GORGEOUS,             // 0x9F
    PKMN_LOCATION_WATER_LABYRINTH,             // 0xA0
    PKMN_LOCATION_FIVE_ISLE_MEADOW,            // 0xA1
    PKMN_LOCATION_MEMORIAL_PILLAR,             // 0xA2
    PKMN_LOCATION_OUTCAST_ISLAND,              // 0xA3
    PKMN_LOCATION_GREEN_PATH,                  // 0xA4
    PKMN_LOCATION_WATER_PATH,                  // 0xA5
    PKMN_LOCATION_RUIN_VALLEY,                 // 0xA6
    PKMN_LOCATION_TRAINER_TOWER_EXTERIOR,      // 0xA7
    PKMN_LOCATION_CANYON_ENTRANCE,             // 0xA8
    PKMN_LOCATION_SEVAULT_CANYON,              // 0xA9
    PKMN_LOCATION_TANOBY_RUINS,                // 0xAA
    PKMN_LOCATION_SEVII_ISLE_22,               // 0xAB
    PKMN_LOCATION_SEVII_ISLE_23,               // 0xAC
    PKMN_LOCATION_SEVII_ISLE_24,               // 0xAD
    PKMN_LOCATION_NAVEL_ROCK_KANTO,            // 0xAE
    PKMN_LOCATION_MT_EMBER,                    // 0xAF
    PKMN_LOCATION_BERRY_FOREST,                // 0xB0
    PKMN_LOCATION_ICEFALL_CAVE,                // 0xB1
    PKMN_LOCATION_ROCKET_WAREHOUSE,            // 0xB2
    PKMN_LOCATION_TRAINER_TOWER,               // 0xB3
    PKMN_LOCATION_DOTTED_HOLE,                 // 0xB4
    PKMN_LOCATION_LOST_CAVE,                   // 0xB5
    PKMN_LOCATION_PATTERN_BUSH,                // 0xB6
    PKMN_LOCATION_ALTERING_CAVE_KANTO,         // 0xB7
    PKMN_LOCATION_TANOBY_CHAMBERS,             // 0xB8
    PKMN_LOCATION_THREE_ISLE_PATH,             // 0xB9
    PKMN_LOCATION_TANOBY_KEY,                  // 0xBA
    PKMN_LOCATION_BIRTH_ISLAND_KANTO,          // 0xBB
    PKMN_LOCATION_MONEAN_CHAMBER,              // 0xBC
    PKMN_LOCATION_LIPTOO_CHAMBER,              // 0xBD
    PKMN_LOCATION_WEEPTH_CHAMBER,              // 0xBE
    PKMN_LOCATION_DILFORD_CHAMBER,             // 0xBF
    PKMN_LOCATION_SCUFIB_CHAMBER,              // 0xC0
    PKMN_LOCATION_RIXY_CHAMBER,                // 0xC1
    PKMN_LOCATION_VIAPOIS_CHAMBER,             // 0xC2
    PKMN_LOCATION_EMBER_SPA,                   // 0xC3
    PKMN_LOCATION_CELADON_DEPT_SPECIAL_AREA,   // 0xC4
    PKMN_LOCATION_AQUA_HIDEOUT,                // 0xC5
    PKMN_LOCATION_MAGMA_HIDEOUT,               // 0xC6
    PKMN_LOCATION_MIRAGE_TOWER,                // 0xC7
    PKMN_LOCATION_BIRTH_ISLAND_HOENN,          // 0xC8
    PKMN_LOCATION_FARAWAY_ISLAND,              // 0xC9
    PKMN_LOCATION_ARTISAN_CAVE,                // 0xCA
    PKMN_LOCATION_MARINE_CAVE,                 // 0xCB
    PKMN_LOCATION_UNDERWATER_MARINE_CAVE,      // 0xCC
    PKMN_LOCATION_TERRA_CAVE,                  // 0xCD
    PKMN_LOCATION_UNDERWATER_ROUTE_105,        // 0xCE
    PKMN_LOCATION_UNDERWATER_ROUTE_125,        // 0xCF
    PKMN_LOCATION_UNDERWATER_ROUTE_129,        // 0xD0
    PKMN_LOCATION_DESERT_UNDERPASS,            // 0xD1
    PKMN_LOCATION_ALTERING_CAVE_HOENN,         // 0xD2
    PKMN_LOCATION_NAVEL_ROCK_HOENN,            // 0xD3
    PKMN_LOCATION_TRAINER_HILL,                // 0xD4
    PKMN_LOCATION_GIFT_EGG,                    // 0xFD
    PKMN_LOCATION_IN_GAME_TRADE,               // 0xFE
    PKMN_LOCATION_FATEFUL_ENCOUNTER,           // 0xFF
};

#endif //CSAV_LOCATIONS_H
