#ifndef MOVES_H
#define MOVES_H

enum Moves {
    MOVE_EMPTY_MOVE    ,  // 0X0
    MOVE_POUND         ,  // 0X1
    MOVE_KARATE_CHOP   ,  // 0X2
    MOVE_DOUBLESLAP    ,  // 0X3
    MOVE_COMET_PUNCH   ,  // 0X4
    MOVE_MEGA_PUNCH    ,  // 0X5
    MOVE_PAY_DAY       ,  // 0X6
    MOVE_FIRE_PUNCH    ,  // 0X7
    MOVE_ICE_PUNCH     ,  // 0X8
    MOVE_THUNDERPUNCH  ,  // 0X9
    MOVE_SCRATCH       ,  // 0XA
    MOVE_VICEGRIP      ,  // 0XB
    MOVE_GUILLOTINE    ,  // 0XC
    MOVE_RAZOR_WIND    ,  // 0XD
    MOVE_SWORDS_DANCE  ,  // 0XE
    MOVE_CUT           ,  // 0XF
    MOVE_GUST          ,  // 0X10
    MOVE_WING_ATTACK   ,  // 0X11
    MOVE_WHIRLWIND     ,  // 0X12
    MOVE_FLY           ,  // 0X13
    MOVE_BIND          ,  // 0X14
    MOVE_SLAM          ,  // 0X15
    MOVE_VINE_WHIP     ,  // 0X16
    MOVE_STOMP         ,  // 0X17
    MOVE_DOUBLE_KICK   ,  // 0X18
    MOVE_MEGA_KICK     ,  // 0X19
    MOVE_JUMP_KICK     ,  // 0X1A
    MOVE_ROLLING_KICK  ,  // 0X1B
    MOVE_SAND_ATTACK   ,  // 0X1C
    MOVE_HEADBUTT      ,  // 0X1D
    MOVE_HORN_ATTACK   ,  // 0X1E
    MOVE_FURY_ATTACK   ,  // 0X1F
    MOVE_HORN_DRILL    ,  // 0X20
    MOVE_TACKLE        ,  // 0X21
    MOVE_BODY_SLAM     ,  // 0X22
    MOVE_WRAP          ,  // 0X23
    MOVE_TAKE_DOWN     ,  // 0X24
    MOVE_THRASH        ,  // 0X25
    MOVE_DOUBLE_EDGE   ,  // 0X26
    MOVE_TAIL_WHIP     ,  // 0X27
    MOVE_POISON_STING  ,  // 0X28
    MOVE_TWINEEDLE     ,  // 0X29
    MOVE_PIN_MISSILE   ,  // 0X2A
    MOVE_LEER          ,  // 0X2B
    MOVE_BITE          ,  // 0X2C
    MOVE_GROWL         ,  // 0X2D
    MOVE_ROAR          ,  // 0X2E
    MOVE_SING          ,  // 0X2F
    MOVE_SUPERSONIC    ,  // 0X30
    MOVE_SONICBOOM     ,  // 0X31
    MOVE_DISABLE       ,  // 0X32
    MOVE_ACID          ,  // 0X33
    MOVE_EMBER         ,  // 0X34
    MOVE_FLAMETHROWER  ,  // 0X35
    MOVE_MIST          ,  // 0X36
    MOVE_WATER_GUN     ,  // 0X37
    MOVE_HYDRO_PUMP    ,  // 0X38
    MOVE_SURF          ,  // 0X39
    MOVE_ICE_BEAM      ,  // 0X3A
    MOVE_BLIZZARD      ,  // 0X3B
    MOVE_PSYBEAM       ,  // 0X3C
    MOVE_BUBBLEBEAM    ,  // 0X3D
    MOVE_AURORA_BEAM   ,  // 0X3E
    MOVE_HYPER_BEAM    ,  // 0X3F
    MOVE_PECK          ,  // 0X40
    MOVE_DRILL_PECK    ,  // 0X41
    MOVE_SUBMISSION    ,  // 0X42
    MOVE_LOW_KICK      ,  // 0X43
    MOVE_COUNTER       ,  // 0X44
    MOVE_SEISMIC_TOSS  ,  // 0X45
    MOVE_STRENGTH      ,  // 0X46
    MOVE_ABSORB        ,  // 0X47
    MOVE_MEGA_DRAIN    ,  // 0X48
    MOVE_LEECH_SEED    ,  // 0X49
    MOVE_GROWTH        ,  // 0X4A
    MOVE_RAZOR_LEAF    ,  // 0X4B
    MOVE_SOLARBEAM     ,  // 0X4C
    MOVE_POISONPOWDER  ,  // 0X4D
    MOVE_STUN_SPORE    ,  // 0X4E
    MOVE_SLEEP_POWDER  ,  // 0X4F
    MOVE_PETAL_DANCE   ,  // 0X50
    MOVE_STRING_SHOT   ,  // 0X51
    MOVE_DRAGON_RAGE   ,  // 0X52
    MOVE_FIRE_SPIN     ,  // 0X53
    MOVE_THUNDERSHOCK  ,  // 0X54
    MOVE_THUNDERBOLT   ,  // 0X55
    MOVE_THUNDER_WAVE  ,  // 0X56
    MOVE_THUNDER       ,  // 0X57
    MOVE_ROCK_THROW    ,  // 0X58
    MOVE_EARTHQUAKE    ,  // 0X59
    MOVE_FISSURE       ,  // 0X5A
    MOVE_DIG           ,  // 0X5B
    MOVE_TOXIC         ,  // 0X5C
    MOVE_CONFUSION     ,  // 0X5D
    MOVE_PSYCHIC       ,  // 0X5E
    MOVE_HYPNOSIS      ,  // 0X5F
    MOVE_MEDITATE      ,  // 0X60
    MOVE_AGILITY       ,  // 0X61
    MOVE_QUICK_ATTACK  ,  // 0X62
    MOVE_RAGE          ,  // 0X63
    MOVE_TELEPORT      ,  // 0X64
    MOVE_NIGHT_SHADE   ,  // 0X65
    MOVE_MIMIC         ,  // 0X66
    MOVE_SCREECH       ,  // 0X67
    MOVE_DOUBLE_TEAM   ,  // 0X68
    MOVE_RECOVER       ,  // 0X69
    MOVE_HARDEN        ,  // 0X6A
    MOVE_MINIMIZE      ,  // 0X6B
    MOVE_SMOKESCREEN   ,  // 0X6C
    MOVE_CONFUSE_RAY   ,  // 0X6D
    MOVE_WITHDRAW      ,  // 0X6E
    MOVE_DEFENSE_CURL  ,  // 0X6F
    MOVE_BARRIER       ,  // 0X70
    MOVE_LIGHT_SCREEN  ,  // 0X71
    MOVE_HAZE          ,  // 0X72
    MOVE_REFLECT       ,  // 0X73
    MOVE_FOCUS_ENERGY  ,  // 0X74
    MOVE_BIDE          ,  // 0X75
    MOVE_METRONOME     ,  // 0X76
    MOVE_MIRROR_MOVE   ,  // 0X77
    MOVE_SELFDESTRUCT  ,  // 0X78
    MOVE_EGG_BOMB      ,  // 0X79
    MOVE_LICK          ,  // 0X7A
    MOVE_SMOG          ,  // 0X7B
    MOVE_SLUDGE        ,  // 0X7C
    MOVE_BONE_CLUB     ,  // 0X7D
    MOVE_FIRE_BLAST    ,  // 0X7E
    MOVE_WATERFALL     ,  // 0X7F
    MOVE_CLAMP         ,  // 0X80
    MOVE_SWIFT         ,  // 0X81
    MOVE_SKULL_BASH    ,  // 0X82
    MOVE_SPIKE_CANNON  ,  // 0X83
    MOVE_CONSTRICT     ,  // 0X84
    MOVE_AMNESIA       ,  // 0X85
    MOVE_KINESIS       ,  // 0X86
    MOVE_SOFTBOILED    ,  // 0X87
    MOVE_HI_JUMP_KICK  ,  // 0X88
    MOVE_GLARE         ,  // 0X89
    MOVE_DREAM_EATER   ,  // 0X8A
    MOVE_POISON_GAS    ,  // 0X8B
    MOVE_BARRAGE       ,  // 0X8C
    MOVE_LEECH_LIFE    ,  // 0X8D
    MOVE_LOVELY_KISS   ,  // 0X8E
    MOVE_SKY_ATTACK    ,  // 0X8F
    MOVE_TRANSFORM     ,  // 0X90
    MOVE_BUBBLE        ,  // 0X91
    MOVE_DIZZY_PUNCH   ,  // 0X92
    MOVE_SPORE         ,  // 0X93
    MOVE_FLASH         ,  // 0X94
    MOVE_PSYWAVE       ,  // 0X95
    MOVE_SPLASH        ,  // 0X96
    MOVE_ACID_ARMOR    ,  // 0X97
    MOVE_CRABHAMMER    ,  // 0X98
    MOVE_EXPLOSION     ,  // 0X99
    MOVE_FURY_SWIPES   ,  // 0X9A
    MOVE_BONEMERANG    ,  // 0X9B
    MOVE_REST          ,  // 0X9C
    MOVE_ROCK_SLIDE    ,  // 0X9D
    MOVE_HYPER_FANG    ,  // 0X9E
    MOVE_SHARPEN       ,  // 0X9F
    MOVE_CONVERSION    ,  // 0XA0
    MOVE_TRI_ATTACK    ,  // 0XA1
    MOVE_SUPER_FANG    ,  // 0XA2
    MOVE_SLASH         ,  // 0XA3
    MOVE_SUBSTITUTE    ,  // 0XA4
    MOVE_STRUGGLE      ,  // 0XA5
    MOVE_SKETCH        ,  // 0XA6
    MOVE_TRIPLE_KICK   ,  // 0XA7
    MOVE_THIEF         ,  // 0XA8
    MOVE_SPIDER_WEB    ,  // 0XA9
    MOVE_MIND_READER   ,  // 0XAA
    MOVE_NIGHTMARE     ,  // 0XAB
    MOVE_FLAME_WHEEL   ,  // 0XAC
    MOVE_SNORE         ,  // 0XAD
    MOVE_CURSE         ,  // 0XAE
    MOVE_FLAIL         ,  // 0XAF
    MOVE_CONVERSION_2  ,  // 0XB0
    MOVE_AEROBLAST     ,  // 0XB1
    MOVE_COTTON_SPORE  ,  // 0XB2
    MOVE_REVERSAL      ,  // 0XB3
    MOVE_SPITE         ,  // 0XB4
    MOVE_POWDER_SNOW   ,  // 0XB5
    MOVE_PROTECT       ,  // 0XB6
    MOVE_MACH_PUNCH    ,  // 0XB7
    MOVE_SCARY_FACE    ,  // 0XB8
    MOVE_FAINT_ATTACK  ,  // 0XB9
    MOVE_SWEET_KISS    ,  // 0XBA
    MOVE_BELLY_DRUM    ,  // 0XBB
    MOVE_SLUDGE_BOMB   ,  // 0XBC
    MOVE_MUD_SLAP      ,  // 0XBD
    MOVE_OCTAZOOKA     ,  // 0XBE
    MOVE_SPIKES        ,  // 0XBF
    MOVE_ZAP_CANNON    ,  // 0XC0
    MOVE_FORESIGHT     ,  // 0XC1
    MOVE_DESTINY_BOND  ,  // 0XC2
    MOVE_PERISH_SONG   ,  // 0XC3
    MOVE_ICY_WIND      ,  // 0XC4
    MOVE_DETECT        ,  // 0XC5
    MOVE_BONE_RUSH     ,  // 0XC6
    MOVE_LOCK_ON       ,  // 0XC7
    MOVE_OUTRAGE       ,  // 0XC8
    MOVE_SANDSTORM     ,  // 0XC9
    MOVE_GIGA_DRAIN    ,  // 0XCA
    MOVE_ENDURE        ,  // 0XCB
    MOVE_CHARM         ,  // 0XCC
    MOVE_ROLLOUT       ,  // 0XCD
    MOVE_FALSE_SWIPE   ,  // 0XCE
    MOVE_SWAGGER       ,  // 0XCF
    MOVE_MILK_DRINK    ,  // 0XD0
    MOVE_SPARK         ,  // 0XD1
    MOVE_FURY_CUTTER   ,  // 0XD2
    MOVE_STEEL_WING    ,  // 0XD3
    MOVE_MEAN_LOOK     ,  // 0XD4
    MOVE_ATTRACT       ,  // 0XD5
    MOVE_SLEEP_TALK    ,  // 0XD6
    MOVE_HEAL_BELL     ,  // 0XD7
    MOVE_RETURN        ,  // 0XD8
    MOVE_PRESENT       ,  // 0XD9
    MOVE_FRUSTRATION   ,  // 0XDA
    MOVE_SAFEGUARD     ,  // 0XDB
    MOVE_PAIN_SPLIT    ,  // 0XDC
    MOVE_SACRED_FIRE   ,  // 0XDD
    MOVE_MAGNITUDE     ,  // 0XDE
    MOVE_DYNAMICPUNCH  ,  // 0XDF
    MOVE_MEGAHORN      ,  // 0XE0
    MOVE_DRAGONBREATH  ,  // 0XE1
    MOVE_BATON_PASS    ,  // 0XE2
    MOVE_ENCORE        ,  // 0XE3
    MOVE_PURSUIT       ,  // 0XE4
    MOVE_RAPID_SPIN    ,  // 0XE5
    MOVE_SWEET_SCENT   ,  // 0XE6
    MOVE_IRON_TAIL     ,  // 0XE7
    MOVE_METAL_CLAW    ,  // 0XE8
    MOVE_VITAL_THROW   ,  // 0XE9
    MOVE_MORNING_SUN   ,  // 0XEA
    MOVE_SYNTHESIS     ,  // 0XEB
    MOVE_MOONLIGHT     ,  // 0XEC
    MOVE_HIDDEN_POWER  ,  // 0XED
    MOVE_CROSS_CHOP    ,  // 0XEE
    MOVE_TWISTER       ,  // 0XEF
    MOVE_RAIN_DANCE    ,  // 0XF0
    MOVE_SUNNY_DAY     ,  // 0XF1
    MOVE_CRUNCH        ,  // 0XF2
    MOVE_MIRROR_COAT   ,  // 0XF3
    MOVE_PSYCH_UP      ,  // 0XF4
    MOVE_EXTREMESPEED  ,  // 0XF5
    MOVE_ANCIENTPOWER  ,  // 0XF6
    MOVE_SHADOW_BALL   ,  // 0XF7
    MOVE_FUTURE_SIGHT  ,  // 0XF8
    MOVE_ROCK_SMASH    ,  // 0XF9
    MOVE_WHIRLPOOL     ,  // 0XFA
    MOVE_BEAT_UP       ,  // 0XFB
    MOVE_FAKE_OUT      ,  // 0XFC
    MOVE_UPROAR        ,  // 0XFD
    MOVE_STOCKPILE     ,  // 0XFE
    MOVE_SPIT_UP       ,  // 0XFF
    MOVE_SWALLOW       ,  // 0X100
    MOVE_HEAT_WAVE     ,  // 0X101
    MOVE_HAIL          ,  // 0X102
    MOVE_TORNMENT      ,  // 0X103
    MOVE_FLATTERS      ,  // 0X104
    MOVE_WILL_O_WISP   ,  // 0X105
    MOVE_MEMENTO       ,  // 0X106
    MOVE_FACADE        ,  // 0X107
    MOVE_FOCUS_PUNCH   ,  // 0X108
    MOVE_SMELLINGSALT  ,  // 0X109
    MOVE_FOLLOW_ME     ,  // 0X10A
    MOVE_NATURE_POWER  ,  // 0X10B
    MOVE_CHARGE        ,  // 0X10C
    MOVE_TAUNT         ,  // 0X10D
    MOVE_HELPING_HAND  ,  // 0X10E
    MOVE_TRICK         ,  // 0X10F
    MOVE_ROLE_PLAY     ,  // 0X110
    MOVE_WISH          ,  // 0X111
    MOVE_ASSIST        ,  // 0X112
    MOVE_INGRAIN       ,  // 0X113
    MOVE_SUPERPOWER    ,  // 0X114
    MOVE_MAGIC_COAT    ,  // 0X115
    MOVE_RECYCLE       ,  // 0X116
    MOVE_REVENGE       ,  // 0X117
    MOVE_BRICK_BREAK   ,  // 0X118
    MOVE_YAWN          ,  // 0X119
    MOVE_KNOCK_OFF     ,  // 0X11A
    MOVE_ENDEAVOR      ,  // 0X11B
    MOVE_ERUPTION      ,  // 0X11C
    MOVE_SKILL_SWAP    ,  // 0X11D
    MOVE_IMPRISON      ,  // 0X11E
    MOVE_REFRESH       ,  // 0X11F
    MOVE_GRUDGE        ,  // 0X120
    MOVE_SNATCH        ,  // 0X121
    MOVE_SECRET_POWER  ,  // 0X122
    MOVE_DIVE          ,  // 0X123
    MOVE_ARM_THRUST    ,  // 0X124
    MOVE_CAMOUFLAGE    ,  // 0X125
    MOVE_TAIL_GLOW     ,  // 0X126
    MOVE_LUSTER_PURGE  ,  // 0X127
    MOVE_MIST_BALL     ,  // 0X128
    MOVE_FEATHERDANCE  ,  // 0X129
    MOVE_TEETER_DANCE  ,  // 0X12A
    MOVE_BLAZE_KICK    ,  // 0X12B
    MOVE_MUD_SPORT     ,  // 0X12C
    MOVE_ICE_BALL      ,  // 0X12D
    MOVE_NEEDLE_ARM    ,  // 0X12E
    MOVE_SLACK_OFF     ,  // 0X12F
    MOVE_HYPER_VOICE   ,  // 0X130
    MOVE_POISON_FANG   ,  // 0X131
    MOVE_CRUSH_CLAW    ,  // 0X132
    MOVE_BLAST_BURN    ,  // 0X133
    MOVE_HYDRO_CANNON  ,  // 0X134
    MOVE_METEOR_MASH   ,  // 0X135
    MOVE_ASTONISH      ,  // 0X136
    MOVE_WEATHER_BALL  ,  // 0X137
    MOVE_AROMATHERAPY  ,  // 0X138
    MOVE_FAKE_TEARS    ,  // 0X139
    MOVE_AIR_CUTTER    ,  // 0X13A
    MOVE_OVERHEAT      ,  // 0X13B
    MOVE_ODOR_SLEUTH   ,  // 0X13C
    MOVE_ROCK_TOMB     ,  // 0X13D
    MOVE_SILVER_WIND   ,  // 0X13E
    MOVE_METAL_SOUND   ,  // 0X13F
    MOVE_GRASSWHISTLE  ,  // 0X140
    MOVE_TICKLE        ,  // 0X141
    MOVE_COSMIC_POWER  ,  // 0X142
    MOVE_WATER_SPOUT   ,  // 0X143
    MOVE_SIGNAL_BEAM   ,  // 0X144
    MOVE_SHADOW_PUNCH  ,  // 0X145
    MOVE_EXTRASENSORY  ,  // 0X146
    MOVE_SKY_UPPERCUT  ,  // 0X147
    MOVE_SAND_TOMB     ,  // 0X148
    MOVE_SHEER_COLD    ,  // 0X149
    MOVE_MUDDY_WATER   ,  // 0X14A
    MOVE_BULLET_SEED   ,  // 0X14B
    MOVE_AERIAL_ACE    ,  // 0X14C
    MOVE_ICICLE_SPEAR  ,  // 0X14D
    MOVE_IRON_DEFENSE  ,  // 0X14E
    MOVE_BLOCK         ,  // 0X14F
    MOVE_HOWL          ,  // 0X150
    MOVE_DRAGON_CLAW   ,  // 0X151
    MOVE_FRENZY_PLANT  ,  // 0X152
    MOVE_BULK_UP       ,  // 0X153
    MOVE_BOUNCE        ,  // 0X154
    MOVE_MUD_SHOT      ,  // 0X155
    MOVE_POISON_TAIL   ,  // 0X156
    MOVE_COVET         ,  // 0X157
    MOVE_VOLT_TACKLE   ,  // 0X158
    MOVE_MAGICAL_LEAF  ,  // 0X159
    MOVE_WATER_SPORT   ,  // 0X15A
    MOVE_CALM_MIND     ,  // 0X15B
    MOVE_LEAF_BLADE    ,  // 0X15C
    MOVE_DRAGON_DANCE  ,  // 0X15D
    MOVE_ROCK_BLAST    ,  // 0X15E
    MOVE_SHOCK_WAVE    ,  // 0X15F
    MOVE_WATER_PULSE   ,  // 0X160
    MOVE_DOOM_DESIRE   ,  // 0X161
    MOVE_PSYCHO_BOOST  ,  // 0X162
    MOVE_SHADOW_RUSH   ,  // 0X164
};

#endif //MOVES_H
