//
// Created by josh on 27/04/2025.
//

#ifndef MOVES_H
#define MOVES_H

enum Moves {
    EMPTY_MOVE    ,  // 0X0
    POUND         ,  // 0X1
    KARATE_CHOP   ,  // 0X2
    DOUBLESLAP    ,  // 0X3
    COMET_PUNCH   ,  // 0X4
    MEGA_PUNCH    ,  // 0X5
    PAY_DAY       ,  // 0X6
    FIRE_PUNCH    ,  // 0X7
    ICE_PUNCH     ,  // 0X8
    THUNDERPUNCH  ,  // 0X9
    SCRATCH       ,  // 0XA
    VICEGRIP      ,  // 0XB
    GUILLOTINE    ,  // 0XC
    RAZOR_WIND    ,  // 0XD
    SWORDS_DANCE  ,  // 0XE
    CUT           ,  // 0XF
    GUST          ,  // 0X10
    WING_ATTACK   ,  // 0X11
    WHIRLWIND     ,  // 0X12
    FLY           ,  // 0X13
    BIND          ,  // 0X14
    SLAM          ,  // 0X15
    VINE_WHIP     ,  // 0X16
    STOMP         ,  // 0X17
    DOUBLE_KICK   ,  // 0X18
    MEGA_KICK     ,  // 0X19
    JUMP_KICK     ,  // 0X1A
    ROLLING_KICK  ,  // 0X1B
    SAND_ATTACK   ,  // 0X1C
    HEADBUTT      ,  // 0X1D
    HORN_ATTACK   ,  // 0X1E
    FURY_ATTACK   ,  // 0X1F
    HORN_DRILL    ,  // 0X20
    TACKLE        ,  // 0X21
    BODY_SLAM     ,  // 0X22
    WRAP          ,  // 0X23
    TAKE_DOWN     ,  // 0X24
    THRASH        ,  // 0X25
    DOUBLE_EDGE   ,  // 0X26
    TAIL_WHIP     ,  // 0X27
    POISON_STING  ,  // 0X28
    TWINEEDLE     ,  // 0X29
    PIN_MISSILE   ,  // 0X2A
    LEER          ,  // 0X2B
    BITE          ,  // 0X2C
    GROWL         ,  // 0X2D
    ROAR          ,  // 0X2E
    SING          ,  // 0X2F
    SUPERSONIC    ,  // 0X30
    SONICBOOM     ,  // 0X31
    DISABLE       ,  // 0X32
    ACID          ,  // 0X33
    EMBER         ,  // 0X34
    FLAMETHROWER  ,  // 0X35
    MIST          ,  // 0X36
    WATER_GUN     ,  // 0X37
    HYDRO_PUMP    ,  // 0X38
    SURF          ,  // 0X39
    ICE_BEAM      ,  // 0X3A
    BLIZZARD      ,  // 0X3B
    PSYBEAM       ,  // 0X3C
    BUBBLEBEAM    ,  // 0X3D
    AURORA_BEAM   ,  // 0X3E
    HYPER_BEAM    ,  // 0X3F
    PECK          ,  // 0X40
    DRILL_PECK    ,  // 0X41
    SUBMISSION    ,  // 0X42
    LOW_KICK      ,  // 0X43
    COUNTER       ,  // 0X44
    SEISMIC_TOSS  ,  // 0X45
    STRENGTH      ,  // 0X46
    ABSORB        ,  // 0X47
    MEGA_DRAIN    ,  // 0X48
    LEECH_SEED    ,  // 0X49
    GROWTH        ,  // 0X4A
    RAZOR_LEAF    ,  // 0X4B
    SOLARBEAM     ,  // 0X4C
    POISONPOWDER  ,  // 0X4D
    STUN_SPORE    ,  // 0X4E
    SLEEP_POWDER  ,  // 0X4F
    PETAL_DANCE   ,  // 0X50
    STRING_SHOT   ,  // 0X51
    DRAGON_RAGE   ,  // 0X52
    FIRE_SPIN     ,  // 0X53
    THUNDERSHOCK  ,  // 0X54
    THUNDERBOLT   ,  // 0X55
    THUNDER_WAVE  ,  // 0X56
    THUNDER       ,  // 0X57
    ROCK_THROW    ,  // 0X58
    EARTHQUAKE    ,  // 0X59
    FISSURE       ,  // 0X5A
    DIG           ,  // 0X5B
    TOXIC         ,  // 0X5C
    CONFUSION     ,  // 0X5D
    PSYCHIC       ,  // 0X5E
    HYPNOSIS      ,  // 0X5F
    MEDITATE      ,  // 0X60
    AGILITY       ,  // 0X61
    QUICK_ATTACK  ,  // 0X62
    RAGE          ,  // 0X63
    TELEPORT      ,  // 0X64
    NIGHT_SHADE   ,  // 0X65
    MIMIC         ,  // 0X66
    SCREECH       ,  // 0X67
    DOUBLE_TEAM   ,  // 0X68
    RECOVER       ,  // 0X69
    HARDEN        ,  // 0X6A
    MINIMIZE      ,  // 0X6B
    SMOKESCREEN   ,  // 0X6C
    CONFUSE_RAY   ,  // 0X6D
    WITHDRAW      ,  // 0X6E
    DEFENSE_CURL  ,  // 0X6F
    BARRIER       ,  // 0X70
    LIGHT_SCREEN  ,  // 0X71
    HAZE          ,  // 0X72
    REFLECT       ,  // 0X73
    FOCUS_ENERGY  ,  // 0X74
    BIDE          ,  // 0X75
    METRONOME     ,  // 0X76
    MIRROR_MOVE   ,  // 0X77
    SELFDESTRUCT  ,  // 0X78
    EGG_BOMB      ,  // 0X79
    LICK          ,  // 0X7A
    SMOG          ,  // 0X7B
    SLUDGE        ,  // 0X7C
    BONE_CLUB     ,  // 0X7D
    FIRE_BLAST    ,  // 0X7E
    WATERFALL     ,  // 0X7F
    CLAMP         ,  // 0X80
    SWIFT         ,  // 0X81
    SKULL_BASH    ,  // 0X82
    SPIKE_CANNON  ,  // 0X83
    CONSTRICT     ,  // 0X84
    AMNESIA       ,  // 0X85
    KINESIS       ,  // 0X86
    SOFTBOILED    ,  // 0X87
    HI_JUMP_KICK  ,  // 0X88
    GLARE         ,  // 0X89
    DREAM_EATER   ,  // 0X8A
    POISON_GAS    ,  // 0X8B
    BARRAGE       ,  // 0X8C
    LEECH_LIFE    ,  // 0X8D
    LOVELY_KISS   ,  // 0X8E
    SKY_ATTACK    ,  // 0X8F
    TRANSFORM     ,  // 0X90
    BUBBLE        ,  // 0X91
    DIZZY_PUNCH   ,  // 0X92
    SPORE         ,  // 0X93
    FLASH         ,  // 0X94
    PSYWAVE       ,  // 0X95
    SPLASH        ,  // 0X96
    ACID_ARMOR    ,  // 0X97
    CRABHAMMER    ,  // 0X98
    EXPLOSION     ,  // 0X99
    FURY_SWIPES   ,  // 0X9A
    BONEMERANG    ,  // 0X9B
    REST          ,  // 0X9C
    ROCK_SLIDE    ,  // 0X9D
    HYPER_FANG    ,  // 0X9E
    SHARPEN       ,  // 0X9F
    CONVERSION    ,  // 0XA0
    TRI_ATTACK    ,  // 0XA1
    SUPER_FANG    ,  // 0XA2
    SLASH         ,  // 0XA3
    SUBSTITUTE    ,  // 0XA4
    STRUGGLE      ,  // 0XA5
    SKETCH        ,  // 0XA6
    TRIPLE_KICK   ,  // 0XA7
    THIEF         ,  // 0XA8
    SPIDER_WEB    ,  // 0XA9
    MIND_READER   ,  // 0XAA
    NIGHTMARE     ,  // 0XAB
    FLAME_WHEEL   ,  // 0XAC
    SNORE         ,  // 0XAD
    CURSE         ,  // 0XAE
    FLAIL         ,  // 0XAF
    CONVERSION_2  ,  // 0XB0
    AEROBLAST     ,  // 0XB1
    COTTON_SPORE  ,  // 0XB2
    REVERSAL      ,  // 0XB3
    SPITE         ,  // 0XB4
    POWDER_SNOW   ,  // 0XB5
    PROTECT       ,  // 0XB6
    MACH_PUNCH    ,  // 0XB7
    SCARY_FACE    ,  // 0XB8
    FAINT_ATTACK  ,  // 0XB9
    SWEET_KISS    ,  // 0XBA
    BELLY_DRUM    ,  // 0XBB
    SLUDGE_BOMB   ,  // 0XBC
    MUD_SLAP      ,  // 0XBD
    OCTAZOOKA     ,  // 0XBE
    SPIKES        ,  // 0XBF
    ZAP_CANNON    ,  // 0XC0
    FORESIGHT     ,  // 0XC1
    DESTINY_BOND  ,  // 0XC2
    PERISH_SONG   ,  // 0XC3
    ICY_WIND      ,  // 0XC4
    DETECT        ,  // 0XC5
    BONE_RUSH     ,  // 0XC6
    LOCK_ON       ,  // 0XC7
    OUTRAGE       ,  // 0XC8
    SANDSTORM     ,  // 0XC9
    GIGA_DRAIN    ,  // 0XCA
    ENDURE        ,  // 0XCB
    CHARM         ,  // 0XCC
    ROLLOUT       ,  // 0XCD
    FALSE_SWIPE   ,  // 0XCE
    SWAGGER       ,  // 0XCF
    MILK_DRINK    ,  // 0XD0
    SPARK         ,  // 0XD1
    FURY_CUTTER   ,  // 0XD2
    STEEL_WING    ,  // 0XD3
    MEAN_LOOK     ,  // 0XD4
    ATTRACT       ,  // 0XD5
    SLEEP_TALK    ,  // 0XD6
    HEAL_BELL     ,  // 0XD7
    RETURN        ,  // 0XD8
    PRESENT       ,  // 0XD9
    FRUSTRATION   ,  // 0XDA
    SAFEGUARD     ,  // 0XDB
    PAIN_SPLIT    ,  // 0XDC
    SACRED_FIRE   ,  // 0XDD
    MAGNITUDE     ,  // 0XDE
    DYNAMICPUNCH  ,  // 0XDF
    MEGAHORN      ,  // 0XE0
    DRAGONBREATH  ,  // 0XE1
    BATON_PASS    ,  // 0XE2
    ENCORE        ,  // 0XE3
    PURSUIT       ,  // 0XE4
    RAPID_SPIN    ,  // 0XE5
    SWEET_SCENT   ,  // 0XE6
    IRON_TAIL     ,  // 0XE7
    METAL_CLAW    ,  // 0XE8
    VITAL_THROW   ,  // 0XE9
    MORNING_SUN   ,  // 0XEA
    SYNTHESIS     ,  // 0XEB
    MOONLIGHT     ,  // 0XEC
    HIDDEN_POWER  ,  // 0XED
    CROSS_CHOP    ,  // 0XEE
    TWISTER       ,  // 0XEF
    RAIN_DANCE    ,  // 0XF0
    SUNNY_DAY     ,  // 0XF1
    CRUNCH        ,  // 0XF2
    MIRROR_COAT   ,  // 0XF3
    PSYCH_UP      ,  // 0XF4
    EXTREMESPEED  ,  // 0XF5
    ANCIENTPOWER  ,  // 0XF6
    SHADOW_BALL   ,  // 0XF7
    FUTURE_SIGHT  ,  // 0XF8
    ROCK_SMASH    ,  // 0XF9
    WHIRLPOOL     ,  // 0XFA
    BEAT_UP       ,  // 0XFB
    FAKE_OUT      ,  // 0XFC
    UPROAR        ,  // 0XFD
    STOCKPILE     ,  // 0XFE
    SPIT_UP       ,  // 0XFF
    SWALLOW       ,  // 0X100
    HEAT_WAVE     ,  // 0X101
    HAIL          ,  // 0X102
    TORNMENT      ,  // 0X103
    FLATTERS      ,  // 0X104
    WILL_O_WISP   ,  // 0X105
    MEMENTO       ,  // 0X106
    FACADE        ,  // 0X107
    FOCUS_PUNCH   ,  // 0X108
    SMELLINGSALT  ,  // 0X109
    FOLLOW_ME     ,  // 0X10A
    NATURE_POWER  ,  // 0X10B
    CHARGE        ,  // 0X10C
    TAUNT         ,  // 0X10D
    HELPING_HAND  ,  // 0X10E
    TRICK         ,  // 0X10F
    ROLE_PLAY     ,  // 0X110
    WISH          ,  // 0X111
    ASSIST        ,  // 0X112
    INGRAIN       ,  // 0X113
    SUPERPOWER    ,  // 0X114
    MAGIC_COAT    ,  // 0X115
    RECYCLE       ,  // 0X116
    REVENGE       ,  // 0X117
    BRICK_BREAK   ,  // 0X118
    YAWN          ,  // 0X119
    KNOCK_OFF     ,  // 0X11A
    ENDEAVOR      ,  // 0X11B
    ERUPTION      ,  // 0X11C
    SKILL_SWAP    ,  // 0X11D
    IMPRISON      ,  // 0X11E
    REFRESH       ,  // 0X11F
    GRUDGE        ,  // 0X120
    SNATCH        ,  // 0X121
    SECRET_POWER  ,  // 0X122
    DIVE          ,  // 0X123
    ARM_THRUST    ,  // 0X124
    CAMOUFLAGE    ,  // 0X125
    TAIL_GLOW     ,  // 0X126
    LUSTER_PURGE  ,  // 0X127
    MIST_BALL     ,  // 0X128
    FEATHERDANCE  ,  // 0X129
    TEETER_DANCE  ,  // 0X12A
    BLAZE_KICK    ,  // 0X12B
    MUD_SPORT     ,  // 0X12C
    ICE_BALL      ,  // 0X12D
    NEEDLE_ARM    ,  // 0X12E
    SLACK_OFF     ,  // 0X12F
    HYPER_VOICE   ,  // 0X130
    POISON_FANG   ,  // 0X131
    CRUSH_CLAW    ,  // 0X132
    BLAST_BURN    ,  // 0X133
    HYDRO_CANNON  ,  // 0X134
    METEOR_MASH   ,  // 0X135
    ASTONISH      ,  // 0X136
    WEATHER_BALL  ,  // 0X137
    AROMATHERAPY  ,  // 0X138
    FAKE_TEARS    ,  // 0X139
    AIR_CUTTER    ,  // 0X13A
    OVERHEAT      ,  // 0X13B
    ODOR_SLEUTH   ,  // 0X13C
    ROCK_TOMB     ,  // 0X13D
    SILVER_WIND   ,  // 0X13E
    METAL_SOUND   ,  // 0X13F
    GRASSWHISTLE  ,  // 0X140
    TICKLE        ,  // 0X141
    COSMIC_POWER  ,  // 0X142
    WATER_SPOUT   ,  // 0X143
    SIGNAL_BEAM   ,  // 0X144
    SHADOW_PUNCH  ,  // 0X145
    EXTRASENSORY  ,  // 0X146
    SKY_UPPERCUT  ,  // 0X147
    SAND_TOMB     ,  // 0X148
    SHEER_COLD    ,  // 0X149
    MUDDY_WATER   ,  // 0X14A
    BULLET_SEED   ,  // 0X14B
    AERIAL_ACE    ,  // 0X14C
    ICICLE_SPEAR  ,  // 0X14D
    IRON_DEFENSE  ,  // 0X14E
    BLOCK         ,  // 0X14F
    HOWL          ,  // 0X150
    DRAGON_CLAW   ,  // 0X151
    FRENZY_PLANT  ,  // 0X152
    BULK_UP       ,  // 0X153
    BOUNCE        ,  // 0X154
    MUD_SHOT      ,  // 0X155
    POISON_TAIL   ,  // 0X156
    COVET         ,  // 0X157
    VOLT_TACKLE   ,  // 0X158
    MAGICAL_LEAF  ,  // 0X159
    WATER_SPORT   ,  // 0X15A
    CALM_MIND     ,  // 0X15B
    LEAF_BLADE    ,  // 0X15C
    DRAGON_DANCE  ,  // 0X15D
    ROCK_BLAST    ,  // 0X15E
    SHOCK_WAVE    ,  // 0X15F
    WATER_PULSE   ,  // 0X160
    DOOM_DESIRE   ,  // 0X161
    PSYCHO_BOOST  ,  // 0X162
    SHADOW_RUSH   ,  // 0X164
};

#endif //MOVES_H
